version: '3.2'
services:
  mosquitto:
    build:
      context: ../iot-event-analytics/docker/mosquitto
      dockerfile: Dockerfile.${ARCH-amd64}
      args:
        - HTTP_PROXY=${DOCKER_HTTP_PROXY}
        - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
    ports:
      - '1883:1883'
    volumes:
      - type: bind
        source: "${CONFIG_DIR}/mosquitto/local"
        target: "/mosquitto/config"
  iotea:
    build:
      context: ../iot-event-analytics
      dockerfile: docker/platform/Dockerfile.slim.${ARCH-amd64}
      args:
        - HTTP_PROXY=${DOCKER_HTTP_PROXY}
        - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
    volumes:
      - type: bind
        source: "${CONFIG_DIR}/iotea"
        target: "/app/docker/platform/config"
  hal-interface-adapter:
    build:
      context: ../
      dockerfile: src/edge.hal-interface-adapter/Dockerfile.${ARCH-amd64}
      args:
        - HTTP_PROXY=${DOCKER_HTTP_PROXY}
        - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
    depends_on:
      - iotea
    volumes:
      - type: bind
        source: "${CONFIG_DIR}/hal-interface-adapter/config-no-kuksa"
        target: "/app/config"
  hal-interface:
    build:
      context: ../
      dockerfile: src/edge.hal-interface/Dockerfile.${ARCH-amd64}
      args:
        - HTTP_PROXY=${DOCKER_HTTP_PROXY}
        - HTTPS_PROXY=${DOCKER_HTTPS_PROXY}
    depends_on:
      - hal-interface-adapter
    volumes:
      - type: bind
        source: "${CONFIG_DIR}/hal-interface"
        target: "/app/config"
